package examples_test

import (
	"testing"

	"github.com/gpdf-dev/gpdf/document"
	"github.com/gpdf-dev/gpdf/htmlpdf"
)

func TestExample_37_HTML_Document(t *testing.T) {
	html := `
	<html>
	<head>
		<style>
		body { font-size: 11pt; line-height: 16pt; }
		h1 { color: #2E7D32; }
		h2 { color: #1565C0; border-bottom: 1px solid #1565C0; padding-bottom: 3pt; }
		.info-box {
			background-color: #E3F2FD;
			padding: 8pt;
			margin: 8pt 0;
			border-left: 3px solid #1565C0;
		}
		blockquote {
			color: #555555;
			font-style: italic;
			border-left: 3px solid #CCCCCC;
			padding-left: 10pt;
		}
		code { font-family: monospace; background-color: #F5F5F5; }
		.footer {
			text-align: center;
			color: #9E9E9E;
			font-size: 9pt;
			margin-top: 20pt;
			border-top: 1px solid #E0E0E0;
			padding-top: 5pt;
		}
		</style>
	</head>
	<body>
		<h1>gpdf HTML Rendering Demo</h1>
		<p>This document demonstrates the Phase 4-A features of gpdf's
		   HTML/CSS rendering engine.</p>

		<h2>Text Formatting</h2>
		<p>gpdf supports <strong>bold</strong>, <em>italic</em>,
		   <u>underline</u>, and <s>strikethrough</s> text.
		   These can be <strong><em>combined</em></strong> freely.</p>

		<h2>Block Elements</h2>
		<div class="info-box">
			<p>This is an info box created with a styled div element.
			   It has a blue left border and light blue background.</p>
		</div>

		<blockquote>
			Simplicity is the ultimate sophistication. — Leonardo da Vinci
		</blockquote>

		<h2>Lists</h2>
		<p>Unordered list:</p>
		<ul>
			<li>Pure Go, zero dependencies</li>
			<li>HTML/CSS to PDF conversion</li>
			<li>CJK text support</li>
		</ul>

		<p>Ordered list:</p>
		<ol>
			<li>Parse HTML</li>
			<li>Apply CSS cascade</li>
			<li>Generate PDF</li>
		</ol>

		<h2>Horizontal Rule</h2>
		<p>Content above the rule.</p>
		<hr>
		<p>Content below the rule.</p>

		<h2>Preformatted Text</h2>
		<pre><code>func main() {
    pdf, _ := gpdf.FromHTML(html)
    os.WriteFile("out.pdf", pdf, 0644)
}</code></pre>

		<p class="footer">Generated by gpdf — Pure Go PDF Library</p>
	</body>
	</html>`

	result, err := htmlpdf.FromHTML(html,
		htmlpdf.WithPageSize(document.A4),
		htmlpdf.WithMargins(document.UniformEdges(document.Mm(20))),
	)
	if err != nil {
		t.Fatalf("FromHTML failed: %v", err)
	}

	data, err := result.Bytes()
	if err != nil {
		t.Fatalf("Bytes failed: %v", err)
	}

	assertValidPDF(t, data)
	writePDF(t, "37_html_document.pdf", data)
	assertMatchesGolden(t, "37_html_document.pdf", data)
}
