package examples_test

import (
	"testing"

	"github.com/gpdf-dev/gpdf/document"
	"github.com/gpdf-dev/gpdf/htmlpdf"
)

func TestExample_38_HTML_Table(t *testing.T) {
	html := `
	<html>
	<head>
		<style>
		body { font-size: 10pt; line-height: 14pt; color: #333; }
		h1 { color: #1a237e; font-size: 18pt; margin-bottom: 4pt; }
		h2 { color: #283593; font-size: 14pt; margin-top: 16pt; margin-bottom: 6pt; }
		p { margin: 6pt 0; }

		/* Basic table styling */
		table {
			width: 100%;
			border-collapse: collapse;
			margin: 8pt 0;
		}
		th {
			background-color: #1a237e;
			color: #ffffff;
			padding: 6pt 8pt;
			text-align: left;
			font-weight: bold;
		}
		td {
			border-bottom: 1px solid #e0e0e0;
			padding: 5pt 8pt;
		}

		/* Attribute selector: stripe even rows */
		tr[class="even"] {
			background-color: #f5f5f5;
		}

		/* Styled table variant */
		table.bordered th,
		table.bordered td {
			border: 1px solid #bdbdbd;
		}
		table.bordered th {
			background-color: #2e7d32;
			color: #ffffff;
		}

		/* Compact table */
		table.compact td,
		table.compact th {
			padding: 2pt 4pt;
			font-size: 9pt;
		}

		/* Caption */
		caption {
			font-style: italic;
			color: #757575;
			margin-bottom: 4pt;
		}

		.total {
			font-weight: bold;
			background-color: #e8eaf6;
		}

		.right { text-align: right; }
		.center { text-align: center; }

		.footer {
			text-align: center;
			color: #9e9e9e;
			font-size: 8pt;
			margin-top: 20pt;
			border-top: 1px solid #e0e0e0;
			padding-top: 4pt;
		}
		</style>
	</head>
	<body>
		<h1>HTML Table Rendering Demo</h1>
		<p>This document demonstrates Phase 4-B table support in gpdf.</p>

		<h2>Basic Table</h2>
		<table>
			<thead>
				<tr>
					<th>Product</th>
					<th>Category</th>
					<th class="right">Price</th>
					<th class="center">Stock</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Widget A</td>
					<td>Hardware</td>
					<td class="right">$29.99</td>
					<td class="center">142</td>
				</tr>
				<tr class="even">
					<td>Widget B</td>
					<td>Hardware</td>
					<td class="right">$49.99</td>
					<td class="center">87</td>
				</tr>
				<tr>
					<td>Service Plan</td>
					<td>Software</td>
					<td class="right">$9.99/mo</td>
					<td class="center">—</td>
				</tr>
				<tr class="even">
					<td>Premium License</td>
					<td>Software</td>
					<td class="right">$199.00</td>
					<td class="center">∞</td>
				</tr>
			</tbody>
		</table>

		<h2>Table with Colspan</h2>
		<table class="bordered">
			<thead>
				<tr>
					<th>Item</th>
					<th class="right">Qty</th>
					<th class="right">Unit Price</th>
					<th class="right">Amount</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Consulting</td>
					<td class="right">10</td>
					<td class="right">$500</td>
					<td class="right">$5,000</td>
				</tr>
				<tr>
					<td>Development</td>
					<td class="right">1</td>
					<td class="right">$10,000</td>
					<td class="right">$10,000</td>
				</tr>
				<tr>
					<td>Support (Annual)</td>
					<td class="right">1</td>
					<td class="right">$2,000</td>
					<td class="right">$2,000</td>
				</tr>
				<tr class="total">
					<td colspan="3" class="right">Total</td>
					<td class="right">$17,000</td>
				</tr>
			</tbody>
		</table>

		<h2>Simple Table (no sections)</h2>
		<table class="compact">
			<tr><th>Name</th><th>Role</th><th>Location</th></tr>
			<tr><td>Alice</td><td>Engineer</td><td>Tokyo</td></tr>
			<tr><td>Bob</td><td>Designer</td><td>Osaka</td></tr>
			<tr><td>Carol</td><td>Manager</td><td>Fukuoka</td></tr>
		</table>

		<p class="footer">Generated by gpdf Phase 4-B — HTML Table Support</p>
	</body>
	</html>`

	result, err := htmlpdf.FromHTML(html,
		htmlpdf.WithPageSize(document.A4),
		htmlpdf.WithMargins(document.UniformEdges(document.Mm(20))),
	)
	if err != nil {
		t.Fatalf("FromHTML failed: %v", err)
	}

	data, err := result.Bytes()
	if err != nil {
		t.Fatalf("Bytes failed: %v", err)
	}

	assertValidPDF(t, data)
	writePDF(t, "38_html_table.pdf", data)
	assertMatchesGolden(t, "38_html_table.pdf", data)
}
